import { invoke } from "@tauri-apps/api/tauri"
import type { NextPage } from "next"
import Head from "next/head"
import LandingPage from "./LandingPage"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Nebula</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LandingPage />
      </main>
    </div>
  )
}

export default Home
